classDiagram
    %%{init: {'flowchart': {'htmlLabels': true}}}%%
    class MeshSimpl...
    class LODGenera...
    class Mesh
    class Mesh
    class FastQuadr...
    class FastQuadr...
    class Program
    class ObjMesh
    class LODLevel
    class MeshDecim...
    class Vector3
    class Vector3
    class LODGenerator
    class Vector3d
    class Vector3d
    class Vector3d
    class MathHelper
    class Vector4d
    class Vector4
    class Vector4d
    class Vector4
    class MathHelper
    class Vector2d
    class Vector2
    class Triangle
    class Vector2
    class Vector2d
    class PipelineS...
    class Symmetric...
    class Symmetric...
    class Vector4i
    class Symmetric...
    class Triangle
    class Vector4i
    class Triangle
    class Vector3i
    class Vector3i
    class Vector2i
    class BoneWeight
    class BoneWeight
    class Vector2i
    class MeshUtils
    class LODGenera...
    class Decimatio...
    class Resizable...
    class Decimatio...
    class LODSettings
    class Resizable...
    class Resizable...
    class Vertex
    class MeshData
    class MeshCombiner
    class Simplific...
    class Logging
    class LODGenerator
    class Decimated...
    class Logging
    class ShowExample
    class BlendShap...
    class MathHelper
    class FaceIndex
    class Vertex
    class MeshUtils...
    class Vertex
    class RendererInfo
    class Decimated...
    class BlendShap...
    class MeshDecim...
    class MeshDecim...
    class UVChannels
    class ExportarG...
    class UVChannels
    class UVChannels
    class ValidateS...
    class BlendShap...
    class PiezaRota
    class ILogger
    class ConsoleLo...
    class Ref
    class BorderVertex

    Decimatio... <|-- FastQuadr...
    Decimatio... <|-- FastQuadr...
    ILogger <|.. ConsoleLo...
