@startuml
title Diagrama de Clases - _Revit_EXE_Geometrias
skinparam classAttributeIconSize 0
skinparam shadowing false
left to right direction
skinparam linetype ortho

!include C:/.TBT/Proyectos/_Revit_EXE_Geometrias/_Documentos generados/classDiagram.part1.puml

@enduml
