flowchart LR
    direction LR
    MeshSimplifier["MeshSimplifier"]
    LODGeneratorHelperEditor["LODGeneratorHelperEditor"]
    Mesh["Mesh"]
    Mesh["Mesh"]
    FastQuadricMeshSimplification["FastQuadricMeshSimplification"]
    FastQuadricMeshSimplification["FastQuadricMeshSimplification"]
    Program["Program"]
    ObjMesh["ObjMesh"]
    LODLevel["LODLevel"]
    MeshDecimatorUtility["MeshDecimatorUtility"]
    Vector3["Vector3"]
    Vector3["Vector3"]
    LODGenerator["LODGenerator"]
    Vector3d["Vector3d"]
    Vector3d["Vector3d"]
    Vector3d["Vector3d"]
    MathHelper["MathHelper"]
    Vector4d["Vector4d"]
    Vector4["Vector4"]
    Vector4d["Vector4d"]
    Vector4["Vector4"]
    MathHelper["MathHelper"]
    Vector2d["Vector2d"]
    Vector2["Vector2"]
    Triangle["Triangle"]
    Vector2["Vector2"]
    Vector2d["Vector2d"]
    PipelineStats["PipelineStats"]
    SymmetricMatrix["SymmetricMatrix"]
    SymmetricMatrix["SymmetricMatrix"]
    Vector4i["Vector4i"]
    SymmetricMatrix["SymmetricMatrix"]
    Triangle["Triangle"]
    Vector4i["Vector4i"]
    Triangle["Triangle"]
    Vector3i["Vector3i"]
    Vector3i["Vector3i"]
    Vector2i["Vector2i"]
    BoneWeight["BoneWeight"]
    BoneWeight["BoneWeight"]
    Vector2i["Vector2i"]
    MeshUtils["MeshUtils"]
    LODGeneratorHelper["LODGeneratorHelper"]
    DecimationAlgorithm["DecimationAlgorithm"]
    ResizableArray["ResizableArray"]
    DecimationAlgorithm["DecimationAlgorithm"]
    LODSettings["LODSettings"]
    ResizableArray["ResizableArray"]
    ResizableArray["ResizableArray"]
    Vertex["Vertex"]
    MeshData["MeshData"]
    MeshCombiner["MeshCombiner"]
    SimplificationOptions["SimplificationOptions"]
    Logging["Logging"]
    LODGenerator["LODGenerator"]
    DecimatedObjectEditor["DecimatedObjectEditor"]
    Logging["Logging"]
    ShowExample["ShowExample"]
    BlendShapeFrameContainer["BlendShapeFrameContainer"]
    MathHelper["MathHelper"]
    FaceIndex["FaceIndex"]
    Vertex["Vertex"]
    MeshUtilsTest["MeshUtilsTest"]
    Vertex["Vertex"]
    RendererInfo["RendererInfo"]
    DecimatedObject["DecimatedObject"]
    BlendShapeContainer["BlendShapeContainer"]
    MeshDecimation["MeshDecimation"]
    MeshDecimation["MeshDecimation"]
    UVChannels["UVChannels"]
    ExportarGeometria["ExportarGeometria"]
    UVChannels["UVChannels"]
    UVChannels["UVChannels"]
    ValidateSimplificationOptionsException["ValidateSimplificationOptio..."]
    BlendShapeFrame["BlendShapeFrame"]
    PiezaRota["PiezaRota"]
    ILogger(["ILogger"])
    ConsoleLogger["ConsoleLogger"]
    Ref["Ref"]
    BorderVertex["BorderVertex"]

    MeshSimplifier -->|usa| MeshUtils
    MeshSimplifier -->|usa| SimplificationOptions
    MeshSimplifier -->|usa| Triangle
    MeshSimplifier -->|usa| Vertex
    MeshSimplifier -->|usa| Ref
    MeshSimplifier -->|usa| Vector3
    MeshSimplifier -->|usa| Vector4
    MeshSimplifier -->|usa| Vector2
    MeshSimplifier -->|usa| BoneWeight
    MeshSimplifier -->|usa| BlendShapeContainer
    MeshSimplifier -->|usa| Mesh
    MeshSimplifier -->|usa| SymmetricMatrix
    MeshSimplifier -->|usa| Vector3d
    MeshSimplifier -->|usa| MathHelper
    MeshSimplifier -->|usa| BorderVertex
    MeshSimplifier -->|usa| ValidateSimplificationOptionsException
    MeshSimplifier -->|usa| ResizableArray
    MeshSimplifier -->|usa| UVChannels
    LODGeneratorHelperEditor -->|usa| LODGeneratorHelper
    LODGeneratorHelperEditor -->|usa| LODGenerator
    Mesh -->|usa| Vector3d
    Mesh -->|usa| Vector3
    Mesh -->|usa| Vector4
    Mesh -->|usa| Vector2
    Mesh -->|usa| BoneWeight
    Mesh -->|usa| MathHelper
    Mesh -->|usa| Vector3d
    Mesh -->|usa| Vector3
    Mesh -->|usa| Vector4
    Mesh -->|usa| Vector2
    Mesh -->|usa| BoneWeight
    Mesh -->|usa| MathHelper
    FastQuadricMeshSimplification -->|hereda| DecimationAlgorithm
    FastQuadricMeshSimplification -->|usa| Vector3d
    FastQuadricMeshSimplification -->|usa| SymmetricMatrix
    FastQuadricMeshSimplification -->|usa| BorderVertex
    FastQuadricMeshSimplification -->|usa| Triangle
    FastQuadricMeshSimplification -->|usa| Vertex
    FastQuadricMeshSimplification -->|usa| Ref
    FastQuadricMeshSimplification -->|usa| Vector3
    FastQuadricMeshSimplification -->|usa| Vector4
    FastQuadricMeshSimplification -->|usa| Vector2
    FastQuadricMeshSimplification -->|usa| BoneWeight
    FastQuadricMeshSimplification -->|usa| Logging
    FastQuadricMeshSimplification -->|usa| MathHelper
    FastQuadricMeshSimplification -->|usa| Mesh
    FastQuadricMeshSimplification -->|usa| ResizableArray
    FastQuadricMeshSimplification -->|usa| UVChannels
    FastQuadricMeshSimplification -->|hereda| DecimationAlgorithm
    FastQuadricMeshSimplification -->|usa| Vector3d
    FastQuadricMeshSimplification -->|usa| SymmetricMatrix
    FastQuadricMeshSimplification -->|usa| BorderVertex
    FastQuadricMeshSimplification -->|usa| Triangle
    FastQuadricMeshSimplification -->|usa| Vertex
    FastQuadricMeshSimplification -->|usa| Ref
    FastQuadricMeshSimplification -->|usa| Vector3
    FastQuadricMeshSimplification -->|usa| Vector4
    FastQuadricMeshSimplification -->|usa| Vector2
    FastQuadricMeshSimplification -->|usa| BoneWeight
    FastQuadricMeshSimplification -->|usa| Logging
    FastQuadricMeshSimplification -->|usa| MathHelper
    FastQuadricMeshSimplification -->|usa| Mesh
    FastQuadricMeshSimplification -->|usa| ResizableArray
    FastQuadricMeshSimplification -->|usa| UVChannels
    Program -->|usa| MeshData
    Program -->|usa| PipelineStats
    Program -->|usa| PiezaRota
    Program -->|usa| Vector3
    Program -->|usa| Vector3d
    Program -->|usa| Mesh
    Program -->|usa| FastQuadricMeshSimplification
    Program -->|usa| MeshDecimation
    Program -->|usa| Vector4
    ObjMesh -->|usa| FaceIndex
    ObjMesh -->|usa| Vector3d
    ObjMesh -->|usa| Vector3
    ObjMesh -->|usa| Vector2
    MeshDecimatorUtility -->|usa| Logging
    MeshDecimatorUtility -->|usa| ConsoleLogger
    MeshDecimatorUtility -->|usa| Vector3d
    MeshDecimatorUtility -->|usa| Vector2
    MeshDecimatorUtility -->|usa| Vector3
    MeshDecimatorUtility -->|usa| Vector4
    MeshDecimatorUtility -->|usa| BoneWeight
    MeshDecimatorUtility -->|usa| Mesh
    MeshDecimatorUtility -->|usa| DecimationAlgorithm
    MeshDecimatorUtility -->|usa| MeshDecimation
    Vector3 -->|usa| Vector3d
    Vector3 -->|usa| Vector3i
    Vector3 -->|usa| MathHelper
    Vector3 -->|usa| Vector3d
    Vector3 -->|usa| Vector3i
    Vector3 -->|usa| MathHelper
    LODGenerator -->|usa| Mesh
    LODGenerator -->|usa| LODGeneratorHelper
    LODGenerator -->|usa| SimplificationOptions
    LODGenerator -->|usa| LODLevel
    LODGenerator -->|usa| MeshSimplifier
    LODGenerator -->|usa| RendererInfo
    LODGenerator -->|usa| MeshCombiner
    LODGenerator -->|usa| Vector3
    Vector3d -->|usa| Vector3
    Vector3d -->|usa| MathHelper
    Vector3d -->|usa| Vector3
    Vector3d -->|usa| Vector3i
    Vector3d -->|usa| MathHelper
    Vector3d -->|usa| Vector3
    Vector3d -->|usa| Vector3i
    Vector3d -->|usa| MathHelper
    MathHelper -->|usa| Vector3
    MathHelper -->|usa| Vector3d
    Vector4d -->|usa| Vector4
    Vector4d -->|usa| Vector4i
    Vector4 -->|usa| Vector4d
    Vector4 -->|usa| Vector4i
    Vector4d -->|usa| Vector4
    Vector4d -->|usa| Vector4i
    Vector4 -->|usa| Vector4d
    Vector4 -->|usa| Vector4i
    MathHelper -->|usa| Vector3
    MathHelper -->|usa| Vector3d
    Vector2d -->|usa| Vector2
    Vector2d -->|usa| Vector2i
    Vector2 -->|usa| Vector2d
    Vector2 -->|usa| Vector2i
    Triangle -->|usa| Vector3d
    Vector2 -->|usa| Vector2d
    Vector2 -->|usa| Vector2i
    Vector2d -->|usa| Vector2
    Vector2d -->|usa| Vector2i
    Vector4i -->|usa| Vector4
    Vector4i -->|usa| Vector4d
    Triangle -->|usa| Vector3d
    Vector4i -->|usa| Vector4
    Vector4i -->|usa| Vector4d
    Triangle -->|usa| Vector3d
    Vector3i -->|usa| Vector3
    Vector3i -->|usa| Vector3d
    Vector3i -->|usa| Vector3
    Vector3i -->|usa| Vector3d
    Vector2i -->|usa| Vector2
    Vector2i -->|usa| Vector2d
    BoneWeight -->|usa| Vector4
    BoneWeight -->|usa| Vector4
    Vector2i -->|usa| Vector2
    Vector2i -->|usa| Vector2d
    MeshUtils -->|usa| Mesh
    MeshUtils -->|usa| Vector3
    MeshUtils -->|usa| Vector4
    MeshUtils -->|usa| BoneWeight
    MeshUtils -->|usa| Vector2
    MeshUtils -->|usa| BlendShapeFrame
    LODGeneratorHelper -->|usa| SimplificationOptions
    LODGeneratorHelper -->|usa| LODLevel
    DecimationAlgorithm -->|usa| MathHelper
    DecimationAlgorithm -->|usa| Mesh
    DecimationAlgorithm -->|usa| MathHelper
    DecimationAlgorithm -->|usa| Mesh
    Vertex -->|usa| Vector3d
    Vertex -->|usa| SymmetricMatrix
    MeshData -->|usa| Vector3
    MeshCombiner -->|usa| Mesh
    MeshCombiner -->|usa| Vector3
    MeshCombiner -->|usa| Vector4
    MeshCombiner -->|usa| BoneWeight
    MeshCombiner -->|usa| MeshUtils
    Logging -->|usa| ILogger
    Logging -->|usa| ConsoleLogger
    LODGenerator -->|usa| Mesh
    LODGenerator -->|usa| DecimationAlgorithm
    LODGenerator -->|usa| MeshDecimatorUtility
    LODGenerator -->|usa| LODSettings
    LODGenerator -->|usa| Vector3
    DecimatedObjectEditor -->|usa| DecimatedObject
    Logging -->|usa| ILogger
    Logging -->|usa| ConsoleLogger
    ShowExample -->|usa| Vector3
    BlendShapeFrameContainer -->|usa| Vector3
    BlendShapeFrameContainer -->|usa| BlendShapeFrame
    BlendShapeFrameContainer -->|usa| ResizableArray
    MathHelper -->|usa| Vector3d
    Vertex -->|usa| Vector3d
    Vertex -->|usa| SymmetricMatrix
    MeshUtilsTest -->|usa| Mesh
    MeshUtilsTest -->|usa| Vector3
    MeshUtilsTest -->|usa| BlendShapeFrame
    MeshUtilsTest -->|usa| MeshUtils
    MeshUtilsTest -->|usa| Vector4
    MeshUtilsTest -->|usa| Vector2
    MeshUtilsTest -->|usa| BoneWeight
    Vertex -->|usa| Vector3d
    Vertex -->|usa| SymmetricMatrix
    RendererInfo -->|usa| Mesh
    DecimatedObject -->|usa| LODSettings
    DecimatedObject -->|usa| LODGenerator
    BlendShapeContainer -->|usa| BlendShapeFrameContainer
    BlendShapeContainer -->|usa| Vector3
    BlendShapeContainer -->|usa| BlendShapeFrame
    MeshDecimation -->|usa| DecimationAlgorithm
    MeshDecimation -->|usa| FastQuadricMeshSimplification
    MeshDecimation -->|usa| Mesh
    MeshDecimation -->|usa| DecimationAlgorithm
    MeshDecimation -->|usa| FastQuadricMeshSimplification
    MeshDecimation -->|usa| Mesh
    UVChannels -->|usa| MeshUtils
    UVChannels -->|usa| ResizableArray
    ExportarGeometria -->|usa| Mesh
    UVChannels -->|usa| Mesh
    UVChannels -->|usa| ResizableArray
    UVChannels -->|usa| Mesh
    UVChannels -->|usa| ResizableArray
    BlendShapeFrame -->|usa| Vector3
    ConsoleLogger -.->|implementa| ILogger
