flowchart LR
    ns_ConvertidorGeometrias["ConvertidorGeometrias"]
    ns_MeshDecimator["MeshDecimator"]
    ns_MeshDecimator_Algorithms["MeshDecimator.Algorithms"]
    ns_MeshDecimator_Collections["MeshDecimator.Collections"]
    ns_MeshDecimator_Loggers["MeshDecimator.Loggers"]
    ns_MeshDecimator_Math["MeshDecimator.Math"]
    ns_MeshDecimator_Unity["MeshDecimator.Unity"]
    ns_MeshDecimator_Unity_Loggers["MeshDecimator.Unity.Loggers"]
    ns_MeshDecimator_UnityEditor["MeshDecimator.UnityEditor"]
    ns_MeshDecimatorTool["MeshDecimatorTool"]
    ns_UnityMeshSimplifier["UnityMeshSimplifier"]
    ns_UnityMeshSimplifier_Editor["UnityMeshSimplifier.Editor"]
    ns_UnityMeshSimplifier_Editor_Tests["UnityMeshSimplifier.Editor.Tests"]
    ns_UnityMeshSimplifier_Internal["UnityMeshSimplifier.Internal"]

    ns_MeshDecimator -->|2| ns_MeshDecimator_Loggers
    ns_MeshDecimator_Algorithms -->|10| ns_UnityMeshSimplifier
    ns_MeshDecimator_Algorithms -->|8| ns_MeshDecimator
    ns_MeshDecimator_Collections -->|2| ns_MeshDecimator
    ns_MeshDecimator_Loggers -->|2| ns_MeshDecimator
    ns_UnityMeshSimplifier -->|8| ns_MeshDecimator
    ns_UnityMeshSimplifier -->|12| ns_MeshDecimator_Math
    ns_MeshDecimator_Unity -->|6| ns_MeshDecimator
    ns_MeshDecimator_Unity -->|1| ns_MeshDecimator_Loggers
    ns_MeshDecimator_Unity -->|1| ns_MeshDecimator_Unity_Loggers
    ns_MeshDecimator_Unity -->|1| ns_UnityMeshSimplifier
    ns_MeshDecimator_Unity -->|4| ns_MeshDecimator_Math
    ns_MeshDecimator_Unity -->|2| ns_MeshDecimator_Algorithms
    ns_MeshDecimator_Math -->|10| ns_UnityMeshSimplifier
    ns__global_ -->|1| ns_MeshDecimator_Math
    ns_UnityMeshSimplifier_Internal -->|6| ns_UnityMeshSimplifier
    ns_UnityMeshSimplifier_Internal -->|3| ns_MeshDecimator_Math
    ns_UnityMeshSimplifier_Internal -->|2| ns_MeshDecimator_Collections
    ns_MeshDecimator_Unity_Loggers -->|1| ns_MeshDecimator
    ns_UnityMeshSimplifier_Editor -->|2| ns_UnityMeshSimplifier
    ns_UnityMeshSimplifier_Editor -->|1| ns_MeshDecimator_Unity
    ns_MeshDecimatorTool -->|2| ns_UnityMeshSimplifier
    ns_MeshDecimatorTool -->|3| ns_MeshDecimator
    ns_MeshDecimatorTool -->|2| ns_MeshDecimator_Math
    ns_MeshDecimator_UnityEditor -->|1| ns_MeshDecimator_Unity
    ns_MeshDecimator -->|8| ns_MeshDecimator_Math
    ns_ConvertidorGeometrias -->|3| ns_MeshDecimator_Math
    ns_ConvertidorGeometrias -->|1| ns_UnityMeshSimplifier
    ns_ConvertidorGeometrias -->|2| ns_MeshDecimator
    ns_ConvertidorGeometrias -->|1| ns_MeshDecimator_Algorithms
    ns_MeshDecimator_Algorithms -->|10| ns_MeshDecimator_Math
    ns_MeshDecimator_Algorithms -->|12| ns_UnityMeshSimplifier_Internal
    ns_MeshDecimator_Algorithms -->|4| ns_MeshDecimator_Collections
    ns_MeshDecimator -->|4| ns_MeshDecimator_Algorithms
    ns_MeshDecimator -->|4| ns_UnityMeshSimplifier
    ns_UnityMeshSimplifier -->|6| ns_UnityMeshSimplifier_Internal
    ns_UnityMeshSimplifier -->|2| ns_MeshDecimator_Collections
    ns_UnityMeshSimplifier_Editor_Tests -->|2| ns_MeshDecimator
    ns_UnityMeshSimplifier_Editor_Tests -->|3| ns_MeshDecimator_Math
    ns_UnityMeshSimplifier_Editor_Tests -->|3| ns_UnityMeshSimplifier
    ns__global_ -->|1| ns_MeshDecimator
