@startuml
title Diagrama de Namespaces - _Revit_EXE_Geometrias
skinparam packageStyle rectangle
left to right direction

package "ConvertidorGeometrias  (4 tipos)" as ns_ConvertidorGeometrias
package "MeshDecimator  (12 tipos)" as ns_MeshDecimator
package "MeshDecimator.Algorithms  (14 tipos)" as ns_MeshDecimator_Algorithms
package "MeshDecimator.Collections  (4 tipos)" as ns_MeshDecimator_Collections
package "MeshDecimator.Loggers  (2 tipos)" as ns_MeshDecimator_Loggers
package "MeshDecimator.Math  (22 tipos)" as ns_MeshDecimator_Math
package "MeshDecimator.Unity  (4 tipos)" as ns_MeshDecimator_Unity
package "MeshDecimator.Unity.Loggers  (1 tipos)" as ns_MeshDecimator_Unity_Loggers
package "MeshDecimator.UnityEditor  (1 tipos)" as ns_MeshDecimator_UnityEditor
package "MeshDecimatorTool  (3 tipos)" as ns_MeshDecimatorTool
package "UnityMeshSimplifier  (17 tipos)" as ns_UnityMeshSimplifier
package "UnityMeshSimplifier.Editor  (2 tipos)" as ns_UnityMeshSimplifier_Editor
package "UnityMeshSimplifier.Editor.Tests  (1 tipos)" as ns_UnityMeshSimplifier_Editor_Tests
package "UnityMeshSimplifier.Internal  (8 tipos)" as ns_UnityMeshSimplifier_Internal

ns_MeshDecimator --> ns_MeshDecimator_Loggers : 2
ns_MeshDecimator_Algorithms --> ns_UnityMeshSimplifier : 10
ns_MeshDecimator_Algorithms --> ns_MeshDecimator : 8
ns_MeshDecimator_Collections --> ns_MeshDecimator : 2
ns_MeshDecimator_Loggers --> ns_MeshDecimator : 2
ns_UnityMeshSimplifier --> ns_MeshDecimator : 8
ns_UnityMeshSimplifier --> ns_MeshDecimator_Math : 12
ns_MeshDecimator_Unity --> ns_MeshDecimator : 6
ns_MeshDecimator_Unity --> ns_MeshDecimator_Loggers : 1
ns_MeshDecimator_Unity --> ns_MeshDecimator_Unity_Loggers : 1
ns_MeshDecimator_Unity --> ns_UnityMeshSimplifier : 1
ns_MeshDecimator_Unity --> ns_MeshDecimator_Math : 4
ns_MeshDecimator_Unity --> ns_MeshDecimator_Algorithms : 2
ns_MeshDecimator_Math --> ns_UnityMeshSimplifier : 10
ns__global_ --> ns_MeshDecimator_Math : 1
ns_UnityMeshSimplifier_Internal --> ns_UnityMeshSimplifier : 6
ns_UnityMeshSimplifier_Internal --> ns_MeshDecimator_Math : 3
ns_UnityMeshSimplifier_Internal --> ns_MeshDecimator_Collections : 2
ns_MeshDecimator_Unity_Loggers --> ns_MeshDecimator : 1
ns_UnityMeshSimplifier_Editor --> ns_UnityMeshSimplifier : 2
ns_UnityMeshSimplifier_Editor --> ns_MeshDecimator_Unity : 1
ns_MeshDecimatorTool --> ns_UnityMeshSimplifier : 2
ns_MeshDecimatorTool --> ns_MeshDecimator : 3
ns_MeshDecimatorTool --> ns_MeshDecimator_Math : 2
ns_MeshDecimator_UnityEditor --> ns_MeshDecimator_Unity : 1
ns_MeshDecimator --> ns_MeshDecimator_Math : 8
ns_ConvertidorGeometrias --> ns_MeshDecimator_Math : 3
ns_ConvertidorGeometrias --> ns_UnityMeshSimplifier : 1
ns_ConvertidorGeometrias --> ns_MeshDecimator : 2
ns_ConvertidorGeometrias --> ns_MeshDecimator_Algorithms : 1
ns_MeshDecimator_Algorithms --> ns_MeshDecimator_Math : 10
ns_MeshDecimator_Algorithms --> ns_UnityMeshSimplifier_Internal : 12
ns_MeshDecimator_Algorithms --> ns_MeshDecimator_Collections : 4
ns_MeshDecimator --> ns_MeshDecimator_Algorithms : 4
ns_MeshDecimator --> ns_UnityMeshSimplifier : 4
ns_UnityMeshSimplifier --> ns_UnityMeshSimplifier_Internal : 6
ns_UnityMeshSimplifier --> ns_MeshDecimator_Collections : 2
ns_UnityMeshSimplifier_Editor_Tests --> ns_MeshDecimator : 2
ns_UnityMeshSimplifier_Editor_Tests --> ns_MeshDecimator_Math : 3
ns_UnityMeshSimplifier_Editor_Tests --> ns_UnityMeshSimplifier : 3
ns__global_ --> ns_MeshDecimator : 1
@enduml
